//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int pro_id { get; set; }
        public string pro_name { get; set; }
        public string pro_image { get; set; }
        public string pro_des { get; set; }
        public int pro_price { get; set; }
        public int pro_fk_cat { get; set; }
        public int pro_fk_user { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
